import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import EnrichmentCard from '@/components/EnrichmentCard';
import styles from '@/styles/AnimalCareResources.module.css';
import SocializationCard from '@/components/SocializationCard';
import TravellingCard from '@/components/TravellingCard';
import DogTrainingCard from '@/components/DogTraining';
import CatTrainingCard from '@/components/CatTraining';
import TrainersCard from '@/components/TrainersCard';


export default function AnimalCareResources() {
    return(
        <>
            <Head>
                <title>haven | animal care resources</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <Header />
                </div>
                <div className={styles.intro}>
                    <h1 className={styles.introTitle}> Animal Care Resources </h1>
                    <p> Discover helpful resources for taking care of your animals</p>
                </div>
                <div className={styles.petBehaviour}>
                    <h1 className={styles.title}> Pet Behaviour </h1>
                    <div className={styles.behaviourCards}>
                        <EnrichmentCard />
                        <SocializationCard />
                        <TravellingCard />
                    </div>
                </div>
                <div className={styles.petTraining}> 
                    <h1 className={styles.title}> Pet Training </h1>
                    <div className={styles.trainingCards}>
                        <DogTrainingCard />
                        <CatTrainingCard />
                        <TrainersCard /> 

                    </div>
                </div>
                <div className={styles.footer}>
                    <Footer />
                </div>
            </main>
        </>
    )
}