import Head from "next/head"
import Header from "@/components/Header"
import styles from '@/styles/Application.module.css'
import Steps from "@/components/Steps"
import Footer from "@/components/Footer"

export default function Application(){
    return(
        <>
        <Head>
            <title>haven | application</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/assets/haven-favi.svg" />
        </Head>

        <main className={styles.main}>
            <div className={styles.header}>
                <Header />
            </div>
            <div className={styles.stepsContainer}>
             <Steps/>
            <div className={styles.formContainer}>
                <h1>Adoption Application</h1>
                <p>Start the process to welcoming your new family member.</p>
            </div>
            </div>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </main>
    </>
)
}