import Head from "next/head";
import styles from '@/styles/Donation.module.css'
import DonationCard from "@/components/DonationCard";

export default function Donation() {
    return (
        <>
            <Head>
                <title>haven | donation</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>
            <main className={styles.main}>
                <div className={styles.container}>
                    <div className={styles.text}>
                        <h1 className={styles.heading}>Support Our Cause</h1>
                        <p className={styles.description}>
                            Help us build a safe haven for animals by donating to a charity of your choice.
                            Your donation will directly contribute to providing shelter, care, and love to abandoned
                            and neglected animals. Payments are processed by Every.org, a nonprofit organization
                            that allows donors to easily make donations to multiple other nonprofits.
                        </p>
                    </div>
                    <DonationCard />
                </div>
            </main>
        </>
    );
}