import Image from "next/image";
import styles from '@/styles/Faq.module.css';
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Accordion from "@/components/Accordion";




export default function Faq() {
    return(
        <>
            <Head>
                <title>haven | faq</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>
            <main className={styles.main}>

                <div className={styles.header}>
                    <Header />
                </div>
            
                <div className={styles.headerIcons}>
                    <Image
                        src="/assets/FaqVectors.svg"
                        alt="haven vectors"
                        width={400}
                        height={550}
                    />
                </div>
                <div className={styles.faqInfo}>
                    <div className={styles.intro}>
                        <h1 className={styles.title}> How to Adopt </h1>
                        <p> Celebrate the journey to a forever bond by exploring our adoption FAQ page. < br />Discover the step-by-step process of welcoming a new furry friend into your home < br /> and learn how you can make a positive impact on their lives. Your guide to making a difference starts here.</p>
                    </div>
                    <div className={styles.discover}>
                        <h1 className={styles.title}>1. Discover our Adoptable Pets</h1>
                        <p> Browse our available animals online. By applying on our adoption platform, you can specify your preferences < br />and receive email notifications when a pet matching your criteria becomes available at one of our facilities.</p>
                    </div>
                    <div className={styles.adoption}>
                        <h1 className={styles.title}>2. Fill out Our Adoption Form</h1>
                        <p> Once you've found a pet you're interested in, make note of their name, ID number, and location on the adoption < br /> file. Fill out our online application form (no account or password required).</p>
                    </div>
                    <div className={styles.meetGreet}>
                        <h1 className={styles.title}>3. Meet & Greet</h1>
                        <p> After we’ve reviewed your application, one of our staff members will arrange a meet–and–greet session where you < br /> can spend time getting to know your potential new companion. This allows for a personal connection and ensures < br />compatibility.</p>
                    </div>
                    <div className={styles.finalize}>
                        <h1 className={styles.title}>4. Finalize the Adoption</h1>
                        <p> If the meet-and-greet goes well and both you and the pet are a good match, we'll proceed with finalizing the adoption! < br /> This includes signing necessary paperwork, paying adoption fees, and receiving guidance on pet care and transitioning < br /> your new friend into their forever home.</p>
                    </div>
                    <div className={styles.postAdoption}>
                        <h1 className={styles.title}>5. Receive Post–Adoption Support</h1>
                        <p> Even after the adoption process is complete, we're here to support you and your new pet. We offer resources, guidance,  < br />and assistance to ensure a smooth transition and a lifelong bond between you and your new addition to the family.</p>
                    </div>
                </div>
                <div className={styles.accordion}>
                    <h1 className={styles.title}>Frequently Asked Questions</h1>
                    <Accordion />
                </div>
                <div className={styles.footer}>
                    <Footer />
                </div>
            </main>
        </>
    )
}