import AdoptBtn from "@/components/AdoptBtn";
import LearnMoreBtn from "@/components/LearnMoreBtn";
import Head from "next/head";
import Image from "next/image";
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <main className={styles.main}>

     <Head>
        <title>haven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/haven-favi.svg" />
      </Head>

      <div className={styles.beforeFold}>
        <div className={styles.foldContent}>
        <div className={styles.taglineCta}>
        <h1 className={styles.tagline}>Find Haven in Every Paw —<br/>Every Heart Deserves a Home.</h1>
        <div className={styles.ctaBtns}>
          <LearnMoreBtn/>
          <AdoptBtn/>
        </div>
          </div>
        <Image
          src="/assets/headericons.svg"
          alt="haven vectors"
          width={550}
          height={650}
        />
        </div>
      </div>

    </main>
  );
}
