import styles from '@/styles/LostAndSurrendered.module.css';
import ContactCard from '@/components/ContactCard';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import { StyleRegistry } from 'styled-jsx';

export default function LostandSurrendered() {
    return(
        <main className={styles.main}>
            <Head>
                <title>Haven</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>
            <div className={styles.header}>
                <Header />
            </div>
            <div className={styles.body}>
                <div className={styles.left}>
                    <h1>Lost & Surrendered Animals</h1>
                    <p>If you find yourself unable to continue providing care for your pet, please don't hesitate to reach out to haven. You can contact us to schedule a visit from an Animal Specialist who will assess your situation and work with you to ensure a smooth and comfortable transition for your pet to the nearest haven shelter.</p>
                </div>
                <div className={styles.right}>
                    <ContactCard />
                </div>
                
            </div>
            <div className={styles.footer}>
             <Footer />
            </div>
        </main>
    );
}
