import styles from '@/styles/Resources.module.css'
import Head from "next/head";
import Header from "@/components/Header";
import DonationResourcesCard from "@/components/DonationResourcesCard";
import AnimalCareResourcesCard from '@/components/AnimalCareResourcesCard';
import AdoptionResourcesCard from '@/components/AdoptionResourcesCard';
import LostSurrenderedResourcesCard from '@/components/LostSurrenderedResourcesCard';
import Footer from "@/components/Footer";
import Image from "next/image";




export default function Resources() {
    return(
        <>

            <Head>
                <title>haven | resources</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>

            <main className={styles.main}>
                <div className={styles.header}>
                    <Header />
                </div>
                <div className={styles.top}>
                    <div className={styles.pug}> 
                        <Image
                            src="/assets/Pug.svg"
                            alt="a vector of a pug"
                            width={100}
                            height={150}
                        />
                    </div>
                    <div className={styles.info}>
                        <div className={styles.title}>
                            <h1>Explore our Resources</h1>
                        </div>
                        <div className={styles.desc}>
                            <p>We give resources to help provide a safe haven for animals.</p>
                        </div>
                    </div>
                </div>
                <div className={styles.cards}>
                    <DonationResourcesCard />
                    <AnimalCareResourcesCard />
                    <AdoptionResourcesCard />
                    <LostSurrenderedResourcesCard />
                </div>
                <div className={styles.footer}>
                    <Footer />
                </div>
                        

            </main>
        </>
    )
}