import styles from '@/styles/Resources.module.css'
import Head from "next/head";


export default function Resources() {
    return(
        <>

            <Head>
                <title>haven | resources</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/haven-favi.svg" />
            </Head>

            <main className={styles.main}>

            </main>
        </>
    )
}